name: 'Epoch Time Comments'
description: 'Comment the time in human readable format for PRs with epoch timers'
author: 'Duinhil'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
  minEpoch:
    description: 'The minimum number that will be identified as an epoch time for comments'
    default: 0
    required: false
  maxLineLength:
    description: 'The maximum line length to be considered for conversion'
    default: 256
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
