name: 'Epoch Time Comments'
description: 'Comment the time in human readable format for PRs with epoch timers'
author: 'Duinhil'
inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
